### ISSUE TITLE
Changing authentification

### ISSUE THREAD

**Issue by KONIKPK** [WodongaTAFE/PSMoodle#10]
we need to change user authentification from manual to LDAP
but get-moodleuser dont return authentification method.

When i try use set-moodleuser i get this:

Get-MoodleUser -UserName username | Set-MoodleUser -Auth LDAP
Set-MoodleUser: Access control exception

**Comment by mabster** [comment]
Hi KONIKPK,

I think this is related to the other "issue" you raised yesterday - something to do with the way your token is configured. You must not have permission to update users. 

I inherited our Moodle configuration (I'd never seen Moodle before) so I'm not 100% sure of how to configure it to make this module work.

If I navigate to Site Administration and switch to the _Server_ tab, I can see a link under the _Web Services_ heading called _External services_. Click on that and I get a list of services, one of which (on our Moodle) is called "REST Webservices". If I click on the _Functions_ link next to that, I can see a list of all the functions that that service has access to. Looking at the list, it looks like you are missing "core_user_update_users", which you should be able to add using the _Add functions_ link at the bottom of the page.

I think every Moodle instance looks a little different because of custom skins etc, but let me know if that helps at all!

I'm going to put an "up for grabs" label on your other issue, because I need someone more experienced with Moodle to help me document the setup!

**Comment by mabster** [comment]
Hopefully this got you going, KONIKPK. I'll close this issue but you can reopen it if you're still having trouble!
