### ISSUE TITLE
New-MoodleCourse

### ISSUE THREAD

**Issue by steadhouse** [WodongaTAFE/PSMoodle#23]
This might be more of a suggestion/feature enhancement than an issue. I noticed one functionality that doesn't quite exist (and perhaps there's a reason) is a command for New-MoodleCourse. 

I might peek at it to see if I can use other functions as a template - but perhaps there is some existing wisdom as to why this might not be a good idea!

Thanks!

**Comment by mabster** [comment]
Heya @steadhouse! Sorry I didn't see this before now.

I don't think the Moodle API provides a way to create a course programmatically. I guess that makes sense, because creating a course requires a lot of human interaction (fleshing out the structure and content).

I'll close this as "won't fix" but do reopen it if you know of an API endpoint that allows for course creation!

Cheers,
Matt
