### ISSUE TITLE
Possible expansion of supported API calls

### ISSUE THREAD

**Issue by pieterjanheyse** [WodongaTAFE/PSMoodle#3]
Thanks for the module, I'm currently implementing automation using Powershell and missing these API calls, so I'm doing them through a direct call and not your nice Powershell module. Maybe you could expand your module to support them? 

core_group_create_groups
local_ws_enrolcohort_add_instance
core_course_import_course

**Comment by mabster** [comment]
Ok I have New-MoodleGroup, Get-MoodleGroup, Get-MoodleGroupMember, Remove-MoodleGroup and Set-MoodleGroup ready to go for the next release.

In PowerShell, "import" means something different from what "core_course_import_course" does. Typically it means creating a new resource from an existing file (like a CSV file). I think I will call it "Copy-MoodleCourse", because that's closer to what's really happening.

**Comment by mabster** [comment]
Ok, I'm publishing the new version now. Copy-MoodleCourse is included, but I can't really test it here so I'll let you try it and get back to me.

I don't have the local_ws_enrolcohort_add_instance endpoint in any of my local Moodle instances so we must not have that plugin. I'll have to pass on that one. Hope that's ok.

**Comment by mabster** [comment]
I also noticed in your Moodle forum post that you're using `core_course_create_categories`, so I've added `New-MoodleCourseCategory`, `Set-MoodleCourseCategory` and `Remove-MoodleCourseCategory`. Will publish that today as well.

**Comment by mabster** [comment]
I'll close this issue now and if you have any problems with the functions I've added, feel free to open a new issue! Same goes for any new functions you need. Sorry I can't help with the plugin one, but if it's structured in a similar way to the core services then I'm sure you can throw together a custom function to call it based on one of my existing ones.
